import Head from 'next/head'
import Header from './components/Header'

import Banner from './components/Banner'
import Category from './components/Category'
export default function Home() {
  return (
    <div >
      <Head>
        <title>LakshmipurWomens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LakshmipursWomen.png" />
      </Head>
      <Header />
      <main className="max-w-screen-2xl mx-auto">
        <Banner></Banner>
        <Category></Category>
      </main>


    </div>
  )
}
