import Head from 'next/head'
import Header from './component/Header'
import image from '../public/slider2.png'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>LakshmipurWomens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LakshmipursWomen.png" />
      </Head>
      <Header />

      <Image src={image} height={600} alt="image" />
    </div>
  )
}
